// Nomes de todos os canais IPC (processo principal ↔ telas). Um lugar só.
module.exports = {
  OPEN: 'open',
  HOME: 'home',
  BACK: 'back',
  KEY: 'key',
  QUIT: 'quit',
  GO_HOME: 'go-home', // principal → tela
  LAUNCH: 'launch',
  EXE_GET: 'exe:get',
  EXE_CHOOSE: 'exe:choose',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  DS4_GET: 'ds4:get',
  DS4_SET: 'ds4:set',
  STORE_WARNINGS: 'store:warnings',
  GAMES_LIST: 'games:list',
  GAMES_LAUNCH: 'games:launch',
  GAMES_ADD_EXE: 'games:addExe',
  GAMES_ADD_FOLDER: 'games:addFolder',
  GAMES_REMOVE: 'games:remove',
  SYSTEM_USER: 'system:user',
  DRM_STATUS: 'drm:status',
  CATALOG_STATUS: 'catalog:status',
  CATALOG_SET_KEY: 'catalog:setKey',
  CATALOG_CLEAR_KEY: 'catalog:clearKey',
  CATALOG_HOME: 'catalog:home',
  CATALOG_TRAILER: 'catalog:trailer',
  CATALOG_SEARCH: 'catalog:search',
  CATALOG_WHERE: 'catalog:where',
  GAMES_RECENT: 'games:recent',
  MYLIST_GET: 'mylist:get',
  MYLIST_TOGGLE: 'mylist:toggle',
  POWER_RUN: 'power:run',
  POWER_LOGIN_GET: 'power:loginGet',
  POWER_LOGIN_SET: 'power:loginSet',
  VOLUME: 'volume',
  COVERS_STATUS: 'covers:status',
  COVERS_SET_KEY: 'covers:setKey',
  COVERS_CLEAR_KEY: 'covers:clearKey',
}
